// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kendoGridRev.Models;

#nullable disable

namespace kendoGridRev.Migrations
{
    [DbContext(typeof(EmpDbContext))]
    partial class EmpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kendoGridRev.Models.Branch", b =>
                {
                    b.Property<int>("Br_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Br_Id"));

                    b.Property<string>("Br_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Br_Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("kendoGridRev.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Br_Id")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Contact")
                        .IsRequired()
                        .HasColumnType("numeric");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Br_Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("kendoGridRev.Models.Employee", b =>
                {
                    b.HasOne("kendoGridRev.Models.Branch", "Branches")
                        .WithMany()
                        .HasForeignKey("Br_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branches");
                });
#pragma warning restore 612, 618
        }
    }
}
